Add Aggregate versioning extension
doctrine-extensions/DoctrineExtensions pull request #2334
Opened 2021-11-20 13:25 UTC by Myks92

Add new extension Aggregate versioning for issue #2333

2021-11-20 20:18 UTC, zakharov-ilia approved these changes

2021-11-20 20:25 UTC, zakharov-ilia commented on src/AggregateVersioning/AggregateVersionListener.php
> +        $entities = [];
I think it's better to use a array_filter() here

2021-11-23 19:10 UTC, phansys reviewed
Congratulations for your first PR @Myks92!
Is this extension compatible with the ODM?

2021-11-23 19:22 UTC, Myks92 commented
> Congratulations for your first PR @Myks92!
Thanks!

> Is this extension compatible with the ODM?
Sorry, ODM not supported. Only ORM. Also not implemented Symfony bundle. I can do it. Only I would like your review about implemented feature.

2021-11-23 20:42 UTC, phansys requested changes

2021-11-23 20:42 UTC, phansys commented on doc/aggregate_versioning.md
> +     * @var OrderLine[]|Collection
```suggestion
     * @var Collection<int, OrderLine>
```

2021-11-23 20:42 UTC, phansys commented on doc/aggregate_versioning.md
> +     * @return OrderLine[]
```suggestion
     * @return Collection<int, OrderLine>
```

2021-11-23 20:42 UTC, phansys commented on src/AggregateVersioning/AggregateVersionListener.php
> +            if ($entity instanceof AggregateRoot) {
How many times this condition can be met?

2021-11-23 20:42 UTC, phansys commented on src/AggregateVersioning/AggregateVersionListener.php
> +                throw new LogicException(sprintf('Method "%s" not exists in class "%s".', $annotation->aggregateRootMethod, get_class($entity)));
```suggestion
                throw new LogicException(sprintf('Method "%s()" not exists in class "%s".', $annotation->aggregateRootMethod, get_class($entity)));
```

2021-11-23 20:42 UTC, phansys commented on src/AggregateVersioning/AggregateVersionListener.php
> +            throw new LogicException(sprintf('Aggregate "%s" must have AggregateVersioning!', get_class($entity)));
```suggestion
            throw new LogicException(sprintf('Aggregate "%s" must have %s.', get_class($entity), AggregateVersioning::class));
```

2021-11-23 20:42 UTC, phansys commented on tests/Gedmo/AggregateVersioning/AggregateVersioningTest.php
> +        if (!$order = $this->em->getRepository(self::ORDER)->find($id)) {
```suggestion
        if (null === $order = $this->em->getRepository(self::ORDER)->find($id)) {
```

2021-11-23 20:58 UTC, Myks92 commented on src/AggregateVersioning/AggregateVersionListener.php
> +            if ($entity instanceof AggregateRoot) {
Сделал возврат, как только нашли агрегированный корень. https://github.com/doctrine-extensions/DoctrineExtensions/pull/2334/commits/663fff28ba20e5ebea9c0b0362edffbdce731700

2021-11-23 22:00 UTC, phansys requested changes

2021-11-23 22:00 UTC, phansys commented on src/AggregateVersioning/AggregateVersionListener.php
> +        $entity = end($entities);
Even if we currently know that the only method calling this one will not pass an empty array as argument 1, we should take care of that case.

2021-11-23 22:04 UTC, phansys commented
>Sorry, ODM not supported. Only ORM. Also not implemented Symfony bundle. I can do it. Only I would like your review about implemented feature.

I'm sorry, but as I'm not using the **Aggregate** extension, I think I'm not able to share a proper feedback about the feature.
I'm leaving comments regarding the syntax and the codebase itself.
I've requested the review from other maintainers too.

2021-11-23 22:50 UTC, Myks92 commented
> > Sorry, ODM not supported. Only ORM. Also not implemented Symfony bundle. I can do it. Only I would like your review about implemented feature.
> 
> I'm sorry, but as I'm not using the **Aggregate** extension, I think I'm not able to share a proper feedback about the feature. I'm leaving comments regarding the syntax and the codebase itself. I've requested the review from other maintainers too. Regarding the Symfony bundle, I think it is not required here, as this package does not provide a bridge for the framework. I guess the best place to bring that feature is [StofDoctrineExtensionsBundle](https://github.com/stof/StofDoctrineExtensionsBundle).

Thanks for the reviews! Made all suggested changes. I am waiting for reviews from other maintainers.

2021-11-24 20:16 UTC, franmomu commented on src/Mapping/Annotation/AggregateVersioning.php
> +final class AggregateVersioning extends Annotation
IMHO we should add attribute support too, at some point support for annotation will be dropped.

2022-01-01 14:24 UTC, Myks92 commented
@phansys Hi! At what stage is PR? Does it make sense for me to continue supporting him? Will it be approved or can it be closed?

2022-07-30 16:04 UTC, closed without merging