allow php8 attributes
doctrine-extensions/DoctrineExtensions pull request #2366
Opened 2021-12-07 16:23 UTC by tacman

This PR follows the pattern in Loggable to allow for PHP 8 attributes.

However, it doesn't quite work yet, when trying to use a class that implements this I get

    Tree object class: App\Entity\Location must have tree metadata at this point

I imagine that in src/Tree/Mapping/Driver/Annotation.php, it is not loading the attributes, but I can't figure out where that's happening.  Can someone point me in the right direction?

2021-12-07 16:47 UTC, tacman commented
I added the Attribute class, and am doing some basic testing now.

2021-12-07 21:55 UTC, franmomu reviewed
thanks for starting this PR!

2021-12-07 21:55 UTC, franmomu commented on src/Mapping/Annotation/Tree.php
> +    public function __construct(array $data = [], ?string $type = null)
All the public fields should be in the constructor, see

https://github.com/doctrine-extensions/DoctrineExtensions/blob/81458019f09ae999c4509e670f64594c6d8f7e3c/src/Mapping/Annotation/Timestampable.php#L26-L48

2021-12-08 01:59 UTC, tacman commented
Thanks, I've fixed that and pushed a change.

My tests are failing, but they seem to be related to Mongo.  I don't have
mongo (or the driver) installed locally, but the github actions failure
seem to have nothing to do with my changes.

On Tue, Dec 7, 2021 at 4:56 PM Fran Moreno ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> thanks for starting this PR!
> ------------------------------
>
> In src/Mapping/Annotation/Tree.php
> <https://github.com/doctrine-extensions/DoctrineExtensions/pull/2366#discussion_r764391605>
> :
>
> > @@ -42,4 +45,21 @@ final class Tree extends Annotation
>       * @deprecated to be removed in 4.0, unused, configure the property on the TreeRoot annotation instead
>       */
>      public $identifierMethod;
> +
> +    /**
> +     * @phpstan-param class-string|null $type
> +     */
> +    public function __construct(array $data = [], ?string $type = null)
>
> All the public fields should be in the constructor, see
>
>
> https://github.com/doctrine-extensions/DoctrineExtensions/blob/81458019f09ae999c4509e670f64594c6d8f7e3c/src/Mapping/Annotation/Timestampable.php#L26-L48
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/doctrine-extensions/DoctrineExtensions/pull/2366#pullrequestreview-825811977>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEXIQIDX3Y5HMSYDQ6AHSTUPZ7HRANCNFSM5JRVMAQQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-12-08 15:46 UTC, tacman commented
I'm stuck. :-(

It _appears_ that the failures have something to do with mongodb.

2021-12-08 15:53 UTC, franmomu commented on src/Mapping/Annotation/Slug.php
> +                                string $unique_base = '',
```suggestion
                                ?string $unique_base = null,
```

2021-12-08 15:59 UTC, franmomu commented
> It _appears_ that the failures have something to do with mongodb.

Looking at the errors:

https://github.com/doctrine-extensions/DoctrineExtensions/runs/4459312433?check_suite_focus=true#step:8:34

it is not only mongodb, and looking at the line

https://github.com/doctrine-extensions/DoctrineExtensions/blob/81458019f09ae999c4509e670f64594c6d8f7e3c/src/Sluggable/SluggableListener.php#L431

something was not right with the `unique_base` (the phpdoc is not right, it should be `string|null`)

2021-12-09 14:36 UTC, franmomu requested changes
thanks @tacman! but there is still some work needed, basically testing.

We need to add support for these attributes in our models like:

https://github.com/doctrine-extensions/DoctrineExtensions/blob/05e0780273389764dc6dcebfcea34bbac84ff6f0/src/Tree/Traits/NestedSetEntity.php#L23-L29

And then, for testing purposes we have to modify the tests in https://github.com/doctrine-extensions/DoctrineExtensions/tree/main/tests/Gedmo/Tree and replace the calls:

`$this->getMockSqliteEntityManager($evm)` -> `$this->getDefaultMockSqliteEntityManager($evm)`
`$this->getMockDocumentManager($evm)` -> `$this->getDefaultDocumentManager($evm)`

This will use AttributeDriver when using PHP >= 8

And for fully test it we should add attributes to the fixtures: https://github.com/doctrine-extensions/DoctrineExtensions/tree/main/tests/Gedmo/Tree/Fixture. This is quite some work that maybe could be done using [rector](https://getrector.org/blog/how-to-upgrade-annotations-to-attributes) (not removing the existing annotation), but I haven't tried it (so far, I've always done it by hand because I was also adding types).

2021-12-09 14:37 UTC, franmomu commented on .github/workflows/coding-standards.yml
> +      - support-attributes
Please remove this line

2021-12-09 15:08 UTC, tacman commented
Sure.  Question -- how do I trigger github actions on my branch?  Or should
I be making changes on my fork's main branch?

On Thu, Dec 9, 2021 at 9:37 AM Fran Moreno ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In .github/workflows/coding-standards.yml
> <https://github.com/doctrine-extensions/DoctrineExtensions/pull/2366#discussion_r765849788>
> :
>
> > @@ -4,6 +4,7 @@ on:
>    push:
>      branches:
>        - main
> +      - support-attributes
>
> Please remove this line
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/doctrine-extensions/DoctrineExtensions/pull/2366#pullrequestreview-827767872>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEXIQNGZQ5TWWNKL3THJCLUQC5JPANCNFSM5JRVMAQQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-12-09 15:14 UTC, franmomu commented
> Sure. Question -- how do I trigger github actions on my branch? Or should I be making changes on my fork's main branch?

hmmm I don't know if you can see the actions here: https://github.com/tacman/DoctrineExtensions/actions or you can create also a PR in you fork

2021-12-09 15:14 UTC, franmomu commented
> > Sure. Question -- how do I trigger github actions on my branch? Or should I be making changes on my fork's main branch?
> 
> hmmm I don't know if you can see the actions here: https://github.com/tacman/DoctrineExtensions/actions or you can also create a PR in you fork

2021-12-20 18:00 UTC, franmomu commented
@tacman if you rebase with the `main` branch, you _only_ have to add the attributes of the Tree extension to tests, the mapping is already done.

2021-12-22 09:53 UTC, franmomu commented
@tacman if you give permissions to push in your repository I'll try to work on this

2021-12-27 15:06 UTC, franmomu commented
Thanks @tacman for starting this PR! I've used your code and added the missing parts in https://github.com/doctrine-extensions/DoctrineExtensions/pull/2388

2021-12-27 15:06 UTC, closed without merging