[Sluggable] Add datetime_immutable as valid type
doctrine-extensions/DoctrineExtensions pull request #2438
Opened 2022-03-22 13:47 UTC by pbreteche

Slug fields already allow datetime and datetimez, all Doctrine date type variations that instanciate \DateTime and \DateTimeImmutable objects should work either.

## [Unreleased]
### Sluggable
#### Added
- Add support for DateTimeImmutable fields

2022-03-27 11:31 UTC, franmomu commented
Thanks @pbreteche! Can you please add a test? I think we don't have any using a `\DateTimeInterface` to generate a slug and that would be awesome and please add an entry to the `CHANGELOG.md` file.

2022-03-30 08:20 UTC, pbreteche commented
@franmomu as you said, I don't find any tests with `\DateTimeInterface`. I hope this is ok with this project coding style.

2022-06-07 20:12 UTC, dritter requested changes
There seems to be a typo in the attribute name..

2022-06-07 20:12 UTC, dritter commented on tests/Gedmo/Sluggable/Fixture/DateTimeTypes/ArticleDate.php
> +    #[Gedmo\Slug(separator: '-', updatable: true, fields: ['title', 'createdAt'], dateFormate: 'Y-m-d')]
```suggestion
    #[Gedmo\Slug(separator: '-', updatable: true, fields: ['title', 'createdAt'], dateFormat: 'Y-m-d')]
```

2022-06-07 20:12 UTC, dritter commented on tests/Gedmo/Sluggable/Fixture/DateTimeTypes/ArticleDateImmutable.php
> +    #[Gedmo\Slug(separator: '-', updatable: true, fields: ['title', 'createdAt'], dateFormate: 'Y-m-d')]
```suggestion
    #[Gedmo\Slug(separator: '-', updatable: true, fields: ['title', 'createdAt'], dateFormat: 'Y-m-d')]
```

2022-06-07 20:12 UTC, dritter commented on tests/Gedmo/Sluggable/Fixture/DateTimeTypes/ArticleDateTime.php
> +    #[Gedmo\Slug(separator: '-', updatable: true, fields: ['title', 'createdAt'], dateFormate: 'Y-m-d')]
```suggestion
    #[Gedmo\Slug(separator: '-', updatable: true, fields: ['title', 'createdAt'], dateFormat: 'Y-m-d')]
```

2022-06-07 20:12 UTC, dritter commented on tests/Gedmo/Sluggable/Fixture/DateTimeTypes/ArticleDateTimeImmutable.php
> +    #[Gedmo\Slug(separator: '-', updatable: true, fields: ['title', 'createdAt'], dateFormate: 'Y-m-d')]
```suggestion
    #[Gedmo\Slug(separator: '-', updatable: true, fields: ['title', 'createdAt'], dateFormat: 'Y-m-d')]
```

2022-06-07 20:12 UTC, dritter commented on tests/Gedmo/Sluggable/Fixture/DateTimeTypes/ArticleDateTimeTz.php
> +    #[Gedmo\Slug(separator: '-', updatable: true, fields: ['title', 'createdAt'], dateFormate: 'Y-m-d')]
```suggestion
    #[Gedmo\Slug(separator: '-', updatable: true, fields: ['title', 'createdAt'], dateFormat: 'Y-m-d')]
```

2022-06-07 20:12 UTC, dritter commented on tests/Gedmo/Sluggable/Fixture/DateTimeTypes/ArticleDateTimeTzImmutable.php
> +    #[Gedmo\Slug(separator: '-', updatable: true, fields: ['title', 'createdAt'], dateFormate: 'Y-m-d')]
```suggestion
    #[Gedmo\Slug(separator: '-', updatable: true, fields: ['title', 'createdAt'], dateFormat: 'Y-m-d')]
```

2022-07-16 18:29 UTC, phansys commented on CHANGELOG.md
>  #### Added
```suggestion
#### Added
- Sluggable: Add support for DateTimeImmutable fields
```

2022-07-16 23:17 UTC, phansys approved these changes

2022-07-16 23:18 UTC, merged

2022-07-16 23:19 UTC, phansys commented
Thank you @pbreteche and @franmomu!