[Loggable] Support embeddable xml mapping
doctrine-extensions/DoctrineExtensions pull request #2477
Opened 2022-06-22 12:51 UTC by eytanProxi

2022-06-22 14:24 UTC, phansys requested changes

2022-06-22 14:24 UTC, phansys commented on src/Loggable/Mapping/Driver/Xml.php
> +        if (in_array($xmlDoctrine->getName(), ['entity', 'document', 'mapped-superclass', 'embeddable'])) {
```suggestion
        if (in_array($xmlDoctrine->getName(), ['entity', 'document', 'mapped-superclass', 'embeddable'], true)) {
```

2022-09-13 14:40 UTC, eytanProxi commented on src/Loggable/Mapping/Driver/Xml.php
> +        if (in_array($xmlDoctrine->getName(), ['entity', 'document', 'mapped-superclass', 'embeddable'])) {
It's done

2023-03-12 15:05 UTC, pierre-H commented
@phansys  : what should I do ?

2023-03-13 01:45 UTC, phansys commented
Hi @pierre-H!
You should add a changelog note with the related changes ([ref.](https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/CONTRIBUTING.md#changelog)) and the required tests to cover this feature.

2024-07-23 10:46 UTC, closed without merging