Issue 2616
doctrine-extensions/DoctrineExtensions pull request #2617
Opened 2023-05-03 16:13 UTC by oleg-andreyev

fixed #2616

2023-09-07 09:56 UTC, phansys commented
Thank you @oleg-andreyev!

Could you please fix the failing tests and add a changelog note for the provided fix?

2023-09-25 20:18 UTC, oleg-andreyev commented
@phansys please approve workflow.

2023-12-22 13:43 UTC, phansys commented
@oleg-andreyev, could you please fix the CI pipeline and add a [changelog note](https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/CONTRIBUTING.md#changelog)?

Thanks in advance.

2023-12-22 15:15 UTC, phansys requested changes

2023-12-22 15:15 UTC, phansys commented on CHANGELOG.md
> +- Fixed bug in `MaterializedPath::removeNode()` when removing entity that has cascade remove on its children, it was using `scheduleForDelete()` instead of `remove()` which is marked as internal and
```suggestion
- Tree: Cascade remove not being triggered on entity children at `MaterializedPath::removeNode()`.
```

2023-12-22 17:14 UTC, phansys approved these changes

2024-03-08 09:57 UTC, oleg-andreyev commented
merge main branch, @phansys @franmomu

2024-06-09 12:21 UTC, franmomu approved these changes

2024-06-09 12:22 UTC, merged

2024-06-09 12:22 UTC, franmomu commented
thanks @oleg-andreyev!