Feature/drop support for php 7.3
doctrine-extensions/DoctrineExtensions pull request #2636
Opened 2023-06-20 06:59 UTC by Chris53897

https://github.com/doctrine-extensions/DoctrineExtensions/issues/2635

Lets see what CI says

2023-07-06 11:57 UTC, stof approved these changes

2023-07-08 20:34 UTC, phansys requested changes
This change should be supported by Rector:
https://github.com/doctrine-extensions/DoctrineExtensions/blob/070f350987f76f12a0f63b82fdfe92b48123e279/rector.php#L24

2023-08-20 09:49 UTC, Chris53897 commented
Using rector as you suggested will introduce a lot of BC Breaks.

@TomasVotruba Is there a safe way to autoupdate with rector for libraries without BC Breaks?

I would suggest to wait until the problems with doctrine/orm 2.16 are fixed.
After that, merge this PR as it is, and improve after that in follow up PRs.

2023-10-29 12:07 UTC, phansys approved these changes
Maybe we could also implement the rule set [`@PHP74Migration`](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/ruleSets/PHP74Migration.rst#rule-set-php74migration) from PHP-CS-Fixer.

2023-10-29 12:57 UTC, merged

2023-10-29 12:57 UTC, franmomu commented
Thanks @Chris53897!